language: elixir
elixir:
  - 1.5.1
otp_release:
  - 19.1

addons:
  - postgresql: '9.4'

services:
  - postgresql

before_script:
  - cp config/travis.exs config/test.exs
  - mix ecto.create
  - mix ecto.migrate
  - phantomjs --wd

script:
  - mix test --trace
